name: ✨ Feature request
description: Suggest something new for the game
labels: [enhancement, priority/0/untriaged]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the feature you're about to suggest.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Your suggestion
    description: What do you want us to implement?
  validations:
    required: true
- type: textarea
  attributes:
    label: Why should this be implemented?
    description: Oh, come on, the title is descriptive enough.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Mockups? Anything that will give us more context about your feature suggestion goes here!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
